---
title: Blog
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: _posts
  values:
    layout: post
    author: sal
    avatar: "/assets/images/avatar1.jpg"
- scope:
    path: _pages
  values:
    layout: page
name: Sanitizer Wristbands
description: Sanitizer Wristbands - Clean & Safe Hands Everyone, All Day, Everyday
logo: assets/images/swb_logo.png
favicon: assets/images/favicon.ico
baseurl: "/"
disqus: ''
email: info@sanitizerwristbands.com
mailchimp-list: ''
include:
- _pages
permalink: "/:title/"
plugins:
- jekyll-feed
- jekyll-sitemap
- jekyll-paginate
- jekyll-seo-tag
authors:
  samuel:
    name: Samuel
    site: ''
    avatar: ''
    bio: ''
    twitter: https://twitter.com/samueljabiodun
  jane:
    name: Olalekan
    site: ''
    avatar: ''
    bio: ''
    email: ''
    twitter: ''
markdown: kramdown
highlighter: rouge
paginate: 10
exclude:
- README.markdown
- package.json
- grunt.js
- Gruntfile.js
- Gruntfile.coffee
- node_modules
